### ISSUE TITLE
paper link to XGBOD failed, cannot connect to www.yuezhao.me

### ISSUE THREAD

**Issue by EricWebsmith** [yzhao062/anomaly-detection-resources#18]
I cannot open to link to the XGBOD paper. 

the following is the error message. I guess I just dont have access right to this url.

Secure Connection Failed

An error occurred during a connection to www.yuezhao.me. PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

**Comment by yzhao062** [comment]
paper link updated.
