### ISSUE TITLE
Suggestion to include "SSD: A self-supervised approach to outlier detection with deep neural networks"

### ISSUE THREAD

**Issue by VSehwag** [yzhao062/anomaly-detection-resources#25]
Title:  **SSD: A Unified Framework for Self-Supervised Outlier Detection**
Link: https://openreview.net/forum?id=v5gjXpmR8J (ICLR 2021)
Code: https://github.com/inspire-group/SSD

**Comment by yzhao062** [comment]
sounds great. will you be open to submitting a PR under the emerging tech section, 4.18.

when we have enough SSL paper, we could add a new section.

btw, congrats on the paper!

**Comment by VSehwag** [comment]
Thanks! I've create a PR. Appreciate it if you can merge it.
