### ISSUE TITLE
About new isolation based anomaly detection methods

### ISSUE THREAD

**Issue by zhuye88** [yzhao062/anomaly-detection-resources#27]
Hi Yue, 

I found your repository is amazing. Just let you know that our research group (the inventor of iForest) recently has proposed new isolation based anomaly detection methods that you may like to include:

1. Ting, Kai Ming, Bi-Cun Xu, Takashi Washio, and Zhi-Hua Zhou. "Isolation Distributional Kernel: A New Tool for Kernel based Anomaly Detection." In Proceedings of the 26th ACM SIGKDD International Conference on Knowledge Discovery & Data Mining, pp. 198-206. 2020.

code: https://github.com/IsolationKernel/Codes/tree/main/IDK

2. Bandaragoda, Tharindu R., Kai Ming Ting, David Albrecht, Fei Tony Liu, Ye Zhu, and Jonathan R. Wells. "Isolation‐based anomaly detection using nearest‐neighbor ensembles." Computational Intelligence 34, no. 4 (2018): 968-998.

code: https://github.com/zhuye88/iNNE

Cheers,
Ye Zhu

**Comment by yzhao062** [comment]
thanks. will consider to add them!
