### ISSUE TITLE
Link of "Which Anomaly Detector should I use?" is broken

### ISSUE THREAD

**Issue by JM-JO** [yzhao062/anomaly-detection-resources#37]
Reference 83: https://federation.edu.au/__data/assets/pdf_file/0011/443666/ICDM2018-Tutorial-Final.pdf is broken.

**Comment by yzhao062** [comment]
Thanks for letting me know. I searched online and also could not find it.

**Comment by JM-JO** [comment]
The paper is still available by purchase:
https://www.computer.org/csdl/proceedings-article/icdm/2018/08594824/17D45WHONnd
and on researchgate:
https://www.researchgate.net/publication/330031613_Which_Outlier_Detector_Should_I_use
