### ISSUE TITLE
Anomaly Detection Using Seasonal Hybrid Extreme Studentized Deviate Test + tidy

### ISSUE THREAD

**Issue by cneskey** [yzhao062/anomaly-detection-resources#9]
https://github.com/hrbrmstr/AnomalyDetection/blob/master/README.md
Anomaly Detection Using Seasonal Hybrid Extreme Studentized Deviate Test

Twitterfolks launched this package in 2014. Many coding and package standards have changed. The package now conforms to CRAN standards.

The plots were nice and all but terribly unnecessary. The two core functions have been modified to only return tidy data frames (tibbles, actually). This makes it easier to chain them without having to deal with list element dereferencing.

Shorter, snake-case aliases have also been provided:

    ad_ts for AnomalyDetectionTs
    ad_vec for AnomalyDetectionVec

The original names are still in the package but the README and examples all use the newer, shorter versions.

The following outstanding PRs from the original repo are included:

    Added in PR #98 (@gggodhwani)
    Added in PR #93 (@nujnimka)
    Added in PR #69 (@randakar)
    Added in PR #44 (@nicolasmiller)
    PR #92 (@caijun) inherently resolved

If those authors find this repo, please add yourselves to the DESCRIPTION as contirbutors.

**Comment by yzhao062** [comment]
Thanks for pointing this out :)
